image: python:3.10

test_py:
  coverage: '/^Code coverage:\s\d+\.\d+$/'
  except:
    changes:
      - "tattler/package/src/tattler/docs/**/*"
  cache:
    key: tattler_cache
    paths:
      - venv/
      - .cache/pip/
      - urlcache.csv
  script:
    # setup: base system
    - WD=$(pwd)
    - echo "Working directory is $WD"
    - echo "Creating venv ..."
    - test venv -nt .gitlab-ci.yml || python -m venv venv
    - . venv/bin/activate
    - pip install coverage
    ## server
    - echo "tattler server"
    - pip install -r ${WD}/package/src/tattler/server/docs/requirements_test.txt
    - pip freeze
    ## sendable
    - cd ${WD}/package/src/tattler/server/sendable/tests
    - PYTHONPATH=.:${WD}/package/src coverage run -m unittest discover
    - cd ${WD}/package/src/tattler/server/tests
    - LOG_LEVEL=debug PYTHONPATH=.:${WD}/package/src coverage run -m unittest discover
    ## plugins
    - cd ${WD}/package/src/tattler/server/plugins/tests
    - PYTHONPATH=.:${WD}/package/src coverage run -m unittest discover
    ## client
    - echo "tattler client"
    - cd ${WD}/package/src/tattler/client/tattler_py
    - pip install -r docs/requirements_test.txt
    - pip freeze
    - cd tests
    - LOG_LEVEL=debug PYTHONPATH=.:${WD}/package/src coverage run -m unittest discover
    ## print coverage information
    - cd $WD
    - coverage combine $(find . -name .coverage)
    - printf 'Code coverage:\t' ; coverage report --omit='**/tests/**' --format=total --precision=2 ; echo ""
    ## packaging
    - echo "tattler server packaging"
    - cd ${WD}/package
    - pip install build
    - python -m build
    - pip install 'dist/tattler-1.1.1-py3-none-any.whl[Jinja]'
