name: Test tattler codebase
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - name: Setup base system
        run: |
          echo "Creating venv ..."
          test venv -nt .gitlab-ci.yml || python -m venv venv
          . venv/bin/activate
          pip install coverage
      - name: Test server module
        run: |
          echo "tattler server"
          pip install -r src/tattler/server/docs/requirements_test.txt
          pip freeze
          pip install -r src/tattler/enterprise/server/docs/requirements_test.txt
      - name: Test sendable module
        run: |
          cd src/tattler/server/sendable/tests
          PYTHONPATH=.:src coverage run -m unittest discover
          cd -
          cd src/tattler/server/tests
          LOG_LEVEL=debug PYTHONPATH=.:src coverage run -m unittest discover
      - name: Test plugins
        run: |
          cd src/tattler/server/plugins/tests
          PYTHONPATH=.:src coverage run -m unittest discover
      - name: Test client
        run: |
          echo "tattler client"
          cd src/tattler/client/tattler_py
          pip install -r docs/requirements_test.txt
          pip freeze
          cd -
          cd tests
          LOG_LEVEL=debug PYTHONPATH=.:src coverage run -m unittest discover
      - name: print coverage information
        run: |
          coverage combine $(find . -name .coverage)
          printf 'Code coverage:\t' ; coverage report --omit='**/tests/**' --format=total --precision=0 ; echo ""
      - name: packaging
        run: |
          echo "tattler server packaging"
          pip install build
          python -m build
          pip install dist/tattler-1.4.0-py3-none-any.whl
      - name: validate links
        run: |
          echo "Validating links"
          cd utils
          python validate_links.py ../src urlcache.csv
