name: Test tattler codebase
on: [push]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          if [ -f src/tattler/server/docs/requirements_test.txt ]; then pip install -r src/tattler/server/docs/requirements_test.txt; fi
          if [ -f src/tattler/client/tattler_py/docs/requirements_test.txt ]; then pip install -r src/tattler/client/tattler_py/docs/requirements_test.txt; fi
      - name: Test sendable module
        run: |
          WD=$(pwd)
          cd src/tattler/server/sendable/tests
          PYTHONPATH=.:${WD}/src coverage run -m unittest discover
          cd ${WD}/src/tattler/server/tests
          LOG_LEVEL=debug PYTHONPATH=.:${WD}/src coverage run -m unittest discover
      - name: Test plugins
        run: |
          WD=$(pwd)
          cd src/tattler/server/plugins/tests
          PYTHONPATH=.:${WD}/src coverage run -m unittest discover
      - name: Test client
        run: |
          WD=$(pwd)
          echo "tattler client"
          cd src/tattler/client/tattler_py
          pip install -r docs/requirements_test.txt
          pip freeze
          cd $WD
          cd tests
          LOG_LEVEL=debug PYTHONPATH=.:${WD}/src coverage run -m unittest discover
      - name: print coverage information
        run: |
          coverage combine $(find . -name .coverage)
          printf 'Code coverage:\t' ; coverage report --omit='**/tests/**' --format=total --precision=0 ; echo ""
      - name: packaging
        run: |
          echo "tattler server packaging"
          pip install build
          python -m build
          pip install dist/tattler-1.4.0-py3-none-any.whl
      - name: validate links
        run: |
          echo "Validating links"
          cd utils
          python validate_links.py ../src urlcache.csv
